### ISSUE TITLE
make all - not deploying everything on AWS

### ISSUE THREAD

**Issue by opsinghis** [aws-samples/aws-serverless-ecommerce-platform#147] opened 2020-11-17 15:11 UTC
Running make all command is not deploying every thing. For example when I log into the console to check my AWS AppSync, there is not services there.

Also there is no service within event bridge. 

I can see functions in lambda and also 4 tables in dynamodb - payment3p, payment, platform-listener and product.

Post make all , I tried to run the make deploy ( assuming this will make an attempt to deploy all components)

`$ make deploy
[*] deploy delivery-pricing
stack_name: ecommerce-dev-delivery-pricing
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7
tags: Domain=ecommerce Service=delivery-pricing Environment=dev

Waiting for changeset to be created..

No changes to deploy. Stack ecommerce-dev-delivery-pricing is up to date
[*] deploy platform
stack_name: ecommerce-dev-platform
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7
tags: Domain=ecommerce Service=platform Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-platform
[*] deploy payment-3p
stack_name: ecommerce-dev-payment-3p
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7
tags: Domain=ecommerce Service=payment-3p Environment=dev

Waiting for changeset to be created..

No changes to deploy. Stack ecommerce-dev-payment-3p is up to date
[*] deploy products
stack_name: ecommerce-dev-products
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 EventBusName=/ecommerce/dev/platform/event-bus/name
tags: Domain=ecommerce Service=products Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-products
[*] deploy users
stack_name: ecommerce-dev-users
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 EventBusName=/ecommerce/dev/platform/event-bus/name
tags: Domain=ecommerce Service=users Environment=dev

Waiting for changeset to be created..

No changes to deploy. Stack ecommerce-dev-users is up to date
[*] deploy payment
stack_name: ecommerce-dev-payment
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 EventBusName=/ecommerce/dev/platform/event-bus/name Payment3PApiUrl=/ecommerce/dev/payment-3p/api/url
tags: Domain=ecommerce Service=payment Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-payment
[*] deploy orders
stack_name: ecommerce-dev-orders
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 DeliveryApiArn=/ecommerce/dev/delivery-pricing/api/arn DeliveryApiUrl=/ecommerce/dev/delivery-pricing/api/url EventBusName=/ecommerce/dev/platform/event-bus/name PaymentApiArn=/ecommerce/dev/payment/api/arn PaymentApiUrl=/ecommerce/dev/payment/api/url ProductsApiArn=/ecommerce/dev/products/api/arn ProductsApiUrl=/ecommerce/dev/products/api/url
tags: Domain=ecommerce Service=orders Environment=dev

Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Include failed with: S3 key [artifacts/dab2d2e81351c2e69ac38a9e8c6612d6] does not exist.
make[1]: *** [deploy] Error 255
make: *** [deploy-orders] Error 2
`

Please let me know how to resolve these missing components.

Regards
Om

**Comment by opsinghis** [comment] 2020-11-17 16:09
I ran the command in following sequence and now I can see all the deployment going through correctly
1. $ make all
2. $ make package
3. $ make deploy

This time it deployed every thing
'
$ make deploy
[*] deploy delivery-pricing
stack_name: ecommerce-dev-delivery-pricing
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7
tags: Domain=ecommerce Service=delivery-pricing Environment=dev

Waiting for changeset to be created..

No changes to deploy. Stack ecommerce-dev-delivery-pricing is up to date
[*] deploy platform
stack_name: ecommerce-dev-platform
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7
tags: Domain=ecommerce Service=platform Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-platform
[*] deploy payment-3p
stack_name: ecommerce-dev-payment-3p
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7
tags: Domain=ecommerce Service=payment-3p Environment=dev

Waiting for changeset to be created..

No changes to deploy. Stack ecommerce-dev-payment-3p is up to date
[*] deploy products
stack_name: ecommerce-dev-products
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 EventBusName=/ecommerce/dev/platform/event-bus/name
tags: Domain=ecommerce Service=products Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-products
[*] deploy users
stack_name: ecommerce-dev-users
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 EventBusName=/ecommerce/dev/platform/event-bus/name
tags: Domain=ecommerce Service=users Environment=dev

Waiting for changeset to be created..

No changes to deploy. Stack ecommerce-dev-users is up to date
[*] deploy payment
stack_name: ecommerce-dev-payment
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 EventBusName=/ecommerce/dev/platform/event-bus/name Payment3PApiUrl=/ecommerce/dev/payment-3p/api/url
tags: Domain=ecommerce Service=payment Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-payment
[*] deploy orders
stack_name: ecommerce-dev-orders
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 DeliveryApiArn=/ecommerce/dev/delivery-pricing/api/arn DeliveryApiUrl=/ecommerce/dev/delivery-pricing/api/url EventBusName=/ecommerce/dev/platform/event-bus/name PaymentApiArn=/ecommerce/dev/payment/api/arn PaymentApiUrl=/ecommerce/dev/payment/api/url ProductsApiArn=/ecommerce/dev/products/api/arn ProductsApiUrl=/ecommerce/dev/products/api/url
tags: Domain=ecommerce Service=orders Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-orders
[*] deploy warehouse
stack_name: ecommerce-dev-warehouse
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 EventBusName=/ecommerce/dev/platform/event-bus/name
tags: Domain=ecommerce Service=warehouse Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-warehouse
[*] deploy delivery
stack_name: ecommerce-dev-delivery
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 EventBusName=/ecommerce/dev/platform/event-bus/name OrdersApiUrl=/ecommerce/dev/orders/api/url OrdersApiArn=/ecommerce/dev/orders/api/arn
tags: Domain=ecommerce Service=delivery Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-delivery
[*] deploy frontend-api
stack_name: ecommerce-dev-frontend-api
environment: dev
parameters: Environment=dev LogLevel=DEBUG RetentionInDays=7 DeliveryPricingApiArn=/ecommerce/dev/delivery-pricing/api/arn DeliveryPricingApiDomain=/ecommerce/dev/delivery-pricing/api/domain DeliveryTableName=/ecommerce/dev/delivery/table/name OrdersTableName=/ecommerce/dev/orders/table/name OrdersCreateOrderArn=/ecommerce/dev/orders/create-order/arn ProductsTableName=/ecommerce/dev/products/table/name UserPoolId=/ecommerce/dev/users/user-pool/id WarehouseTableName=/ecommerce/dev/warehouse/table/name
tags: Domain=ecommerce Service=frontend-api Environment=dev

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - ecommerce-dev-frontend-api
'

**Comment by nmoutschen** [comment] 2020-11-17 19:08
Hi and thanks for reaching out!

Seems that everything is working on your end so I'll close this ticket.

For reference, the command `make all` does a few more things than just package and deploy (see https://github.com/aws-samples/aws-serverless-ecommerce-platform/blob/master/docs/make_targets.md#project-level-target). If you have a failure and try to run again, it's possible that some services are not built or packaged. In your first message, you can see the following error message: `Transform AWS::Include failed with: S3 key [artifacts/dab2d2e81351c2e69ac38a9e8c6612d6] does not exist.` This would be caused by an issue in the packaging step.

If you have issues there, it's best to do `make all`. If you have an issue with a single service, you can do `make all-$SERVICE`.

**Closed by nmoutschen** 2020-11-17 19:08 UTC
